[build]
  command = "ng build && ng run portfolio:ssr"
  publish = "dist/portfolio/browser"

[build.environment]
  NETLIFY_USE_ANGULAR = "true"

[[plugins]]
  package = "@netlify/angular-runtime"

# Redirection pour la page d'accueil
[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/"
  to = "/en-US"
  status = 302
