[build]
  command = "npm run build:netlify"
  publish = "dist/portfolio/browser"

[build.environment]
  NETLIFY_USE_ANGULAR = "true"
  NODE_VERSION = "20.10.0"

[[plugins]]
  package = "@netlify/angular-runtime"

[functions]
  node_bundler = "esbuild"

# Redirection pour la page d'accueil
[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/"
  to = "/en-US"
  status = 302

# SPA fallback pour chaque langue
[[redirects]]
  from = "/fr/*"
  to = "/fr/index.html"
  status = 200

[[redirects]]
  from = "/en-US/*"
  to = "/en-US/index.html"
  status = 200

# SPA fallback général
[[redirects]]
  from = "/*"
  to = "/fr/index.html"
  status = 200
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/*"
  to = "/en-US/index.html"
  status = 200
