[[redirects]]
  from = "/fr/*"
  to = "/fr/index.html"
  status = 200

[[redirects]]
  from = "/en-US/*"
  to = "/en-US/index.html"
  status = 200

# Redirection de la racine vers la locale appropriée
[[redirects]]
  from = "/"
  to = "/fr/"
  status = 302
  force = true

[[redirects]]
  from = "/"
  to = "/en-US/"
  status = 302
  conditions = {Language = ["en-US*"]}
